#pragma once

#define ERROR_CODE 1
#define LOGIN_CODE 2
#define SIGNUP_CODE 3
#define LOGOUT_CODE 4
#define GET_ROOMS_CODE 5
#define GET_PLAYERS_IN_ROOM_CODE 6
#define GET_JOIN_ROOMS_CODE 7
#define GET_CREATE_ROOMS_CODE 8
#define GET_STATISTICS_CODE 9